version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # L'application sera accessible sur http://localhost:8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edoc
      MYSQL_USER: root
      MYSQL_PASSWORD: rodme09*
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

